apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: {{NAMESPACE}}
  labels:
    app: springboot-app
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      # imagePullSecrets:
      # - name: regcred
      containers:
        - name: springboot-app
          image: {{IMAGE}}
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "{{ENV}}"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: {{NAMESPACE}}
  labels:
    app: springboot-app
spec:
  type: LoadBalancer
  selector:
    app: springboot-app
  ports:
    - port: 80
      targetPort: 8080
